### ISSUE TITLE
Allow to disable specific rules

### ISSUE THREAD

**Issue by javiereguiluz** [OskarStark/doctor-rst#1340]
Right now you can configure the rules to consider for the analysis:

```yaml
rules:
    american_english: ~
    avoid_repetetive_words: ~
    # ...
```

Rules not included in the list are ignored. The problem of this approach is that you'll miss all the new rules added by this nice project!

In one of my applications what I need is _"include all present and future DOCtor-RST rules except one specific rule"_. This is what I'd need:

```yaml
excluded_rules:
    yaml_instead_of_yml_suffix: ~
```

I'm adding this issue in case others have the same need and can add some comment to see if there's interest about this. Thanks.
