### ISSUE TITLE
[Question] Does this action need a previous docker configuration?

### ISSUE THREAD

**Issue by codebydant** [OskarStark/doctor-rst#1386]
Hi @OskarStark,

Greetings.

I have been running this action according to the example, and I was wondering if a docker login step is needed.

I am using `v1.44.1` and is a **private** repository

## Workflow

```yml
# workflow to run a continuous integration pipeline
name: CI Pipeline DOCS

on:
  # event to trigger workflow when opening a pull request
  pull_request:
    # event type related to pull request
    types: [opened, reopened, synchronize]
    # only run this workflow when a reStructuredText file is updated in the following path
    paths:
      - "docs/**"

jobs:

  stale:
    name: Sphinx Lint
    runs-on: ubuntu-22.04

    steps:

      # clones current repository
      - name: Checkout current repository
        uses: actions/checkout@v3.3.0

      - name: "Create cache dir"
        run: mkdir .cache

      - name: "Extract base branch name"
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_BASE_REF:=${GITHUB_REF##*/}})"
        id: extract_base_branch

      - name: "Cache DOCtor-RST"
        uses: actions/cache@v2
        with:
            path: .cache
            key: doctor-rst-${{ runner.os }}-${{ steps.extract_base_branch.outputs.branch }}
            restore-keys: |
                doctor-rst-${{ runner.os }}-
                doctor-rst- 

      - name: DOCtor-RST
        uses: docker://oskarstark/doctor-rst@1.44.1
        with:
          args: --short --error-format=github --cache-file=/github/workspace/.cache/doctor-rst.cache
        env:
          DOCS_DIR: "docs/"
```

## Log
```bash
/usr/bin/docker pull oskarstark/doctor-rst@1.44.1
  invalid reference format
  Warning: Docker pull failed with exit code 1, back off 4.415 seconds before retry.
  /usr/bin/docker pull oskarstark/doctor-rst@1.44.1
  invalid reference format
  Warning: Docker pull failed with exit code 1, back off 2.39 seconds before retry.
  /usr/bin/docker pull oskarstark/doctor-rst@1.44.1
  invalid reference format
Error: Docker pull failed with exit code 1
```

## Aditional context

![Screenshot from 2023-04-25 09-33-38](https://user-images.githubusercontent.com/115469901/234310679-f2935c42-670a-4bf2-895c-1f23ccaa030a.png)
