### ISSUE TITLE
Disable in some paths the rule that checks versions

### ISSUE THREAD

**Issue by javiereguiluz** [OskarStark/doctor-rst#650]
Example of the failure: https://github.com/javiereguiluz/symfony-docs/runs/545604472

In Symfony Docs, all articles under `/frontend/encore/*` talk about Symfony Encore, which uses a different versioning than Symfony framework. Could we disable this rule for these articles only? Thanks!

**Comment by smoench** [comment]
You can prevent this error by adding this to the whitelist as followed: https://github.com/symfony/symfony-docs/blob/master/.doctor-rst.yaml#L70

**Comment by javiereguiluz** [comment]
You are right ... but, if possible, I'd prefer to not do that because it's inefficient (unlike Symfony, there are many new versions in Encore). Thanks.

**Comment by OskarStark** [comment]
Javier I already thought about this, but in a different way. What about having sth like a baseline like PHPStan have ?

**Comment by smoench** [comment]
Whitelist (should be renamed to `ignoreErrors`) and Baseline are mostly the same. People might think they have done something wrong. This could be a stopper for contributing to the docs.

My proposal would be one configuration file per independent project. This means we must extend the configuration to define pathes to analyse and excluded ones.

**Comment by OskarStark** [comment]
Sounds good, but this must be possible per rule

**Comment by javiereguiluz** [comment]
You know this application much better than me ... so maybe my following comment is absurd, but anyway --> I think you are complicating things too much. This is what I'd do (in case it makes sense):

```yaml
# Before
rules:
    versionadded_directive_should_have_version: ~
    deprecated_directive_should_have_version: ~
    use_deprecated_directive_instead_of_versionadded: ~
    versionadded_directive_major_version:
        major_version: 5
    versionadded_directive_min_version:
        min_version: '5.0'
    deprecated_directive_major_version:
        major_version: 5
    deprecated_directive_min_version:
        min_version: '5.0'
    # ...

# After
rules:
    versionadded_directive:
        require_version: true
        major_version: 5
        min_version: '5.0'
        ignore_for: ['/frontend/encore/**']
    deprecated_directive:
        require_version: true
        major_version: 5
        min_version: '5.0'
    # ...
```
