### ISSUE TITLE
[Bug] Please do not use ".. code-block:: php", use "::" instead after note block 

### ISSUE THREAD

**Issue by sstok** [OskarStark/doctor-rst#784]
With configuration file:

<details>

```yaml
rules:
    american_english: ~
    avoid_repetetive_words: ~
    blank_line_after_directive: ~
    blank_line_before_directive: ~
    composer_dev_option_not_at_the_end: ~
    correct_code_block_directive_based_on_the_content: ~
    deprecated_directive_should_have_version: ~
    ensure_order_of_code_blocks_in_configuration_block: ~
    extend_abstract_controller: ~
    extension_xlf_instead_of_xliff: ~
    indention: ~
    lowercase_as_in_use_statements: ~
    max_blank_lines:
        max: 2
    no_app_console: ~
    no_blank_line_after_filepath_in_php_code_block: ~
    no_blank_line_after_filepath_in_twig_code_block: ~
    no_blank_line_after_filepath_in_xml_code_block: ~
    no_blank_line_after_filepath_in_yaml_code_block: ~
    no_brackets_in_method_directive: ~
    no_composer_req: ~
    no_explicit_use_of_code_block_php: ~
    no_inheritdoc: ~
    no_namespace_after_use_statements: ~
    no_php_open_tag_in_code_block_php_directive: ~
    no_space_before_self_xml_closing_tag: ~
    ordered_use_statements: ~
    php_prefix_before_bin_console: ~
    replace_code_block_types: ~
    replacement: ~
    short_array_syntax: ~
    space_between_label_and_link_in_doc: ~
    space_between_label_and_link_in_ref: ~
    typo: ~
    unused_links: ~
    use_deprecated_directive_instead_of_versionadded: ~
    use_https_xsd_urls: ~
    valid_inline_highlighted_namespaces: ~
    valid_use_statements: ~
    versionadded_directive_should_have_version: ~
    yaml_instead_of_yml_suffix: ~
    yarn_dev_option_at_the_end: ~
    #    no_app_bundle: ~

    #   master
#    versionadded_directive_major_version:
#        major_version: 5
#
#    versionadded_directive_min_version:
#        min_version: '5.0'
#
#    deprecated_directive_major_version:
#        major_version: 5
#
#    deprecated_directive_min_version:
#        min_version: '5.0'

# do not report as violation
whitelist:
    regex:
        - '/``.yml``/'
        - '/rst-class/'
    lines:
        - 'The bin/console Command'
        - '.. code-block:: twig'

```
</details>

The following rst doc:

```
To create a FieldSet you can use the ``FieldSetBuilder`` or create a custom
:doc:`FieldSetConfigurator <creating_reusable_fieldsets>`.

.. note::

    Using a ``FieldSetConfigurator`` is mandatory if you plan to serialize
    the condition, it provides a central point to (lazily) load FieldSet configurations.

.. code-block:: php
    :linenos:

    use Rollerworks\Component\Search\Extension\Core\Type\TextType;
    use Rollerworks\Component\Search\Extension\Core\Type\IntegerType;

    // ...

    $userFieldSet = $searchFactory->createFieldSetBuilder()
        ->add('id', IntegerType::class)
        ->add('username', TextType::class)
        ->add('firstName', TextType::class)
        ->add('lastName', TextType::class)
        ->getFieldSet();
```

Reports that `::` should be used instead of `".. code-block:: php"`, but this not possible to my knowledge, as `::` directly at the start of line is incorrect. And the previous text is a note block.
