### ISSUE TITLE
Configuration file .doctor-rst.yaml is not optional

### ISSUE THREAD

**Issue by mloskot** [OskarStark/doctor-rst#954]
I've added this GA workflow file:

```yaml
name: "Lint: documentation"

on: [push, pull_request]

jobs:
  reStructuredText:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://oskarstark/doctor-rst
      with:
        args: --short --error-format=github
      env:
        DOCS_DIR: 'doc/'
```

and the the action throws

```console
Error: ] Could not find config file: /github/workspace/doc/.doctor-rst.yaml
```

Apparently, the `.doctor-rst.yaml` is required but such requirement seems not documented anywhere.

https://github.com/OskarStark/doctor-rst/search?q=.doctor-rst.yaml is offering only two issues: #322 and #650 and nothing else.
